### ISSUE TITLE
issue in sub folders / sub directories

### ISSUE THREAD

**Issue by nikkithought** [nikalsh/vuepress-auto-sidebar#4]
```
[vuepress] No matching page found for sidebar item "/departments/adminstration/index"
[vuepress] No matching page found for sidebar item "/departments/adminstration/index"
[vuepress] No matching page found for sidebar item "/departments/adminstration/index"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <GlobalLayout>
                   <Root>
[vuepress] No matching page found for sidebar item "/projects/Term1/index"
[vuepress] No matching page found for sidebar item "/projects/Term1/index"
[vuepress] No matching page found for sidebar item "/projects/Term1/index"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <GlobalLayout>
                   <Root>
error Error rendering /departments/adminstration/: false
undefined
error Error rendering /projects/Term1/: false
undefined
TypeError: Cannot read property 'match' of undefined
    at getHash (node_modules/@vuepress/theme-default/util/index.js:13:21)
    at isActive (node_modules/@vuepress/theme-default/util/index.js:47:19)
    at render (node_modules/@vuepress/theme-default/components/SidebarLink.vue:25:0)
    at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:83:0)
    at createFunctionalComponent (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3052:30)
    at createComponent (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3225:12)
    at _createElement (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3415:15)
    at createElement (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3347:10)
    at vm._c (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3484:42)
    at 1.server-bundle.js:836:492
    at Proxy.renderList (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:2624:16)
    at Proxy.SidebarLinksvue_type_template_id_1da4684a_render (node_modules/@vuepress/theme-default/components/SidebarLinks.vue?e830:1:152)
    at VueComponent.Vue._render (/github/workspace/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
    at resolve (/github/workspace/node_modules/vue-server-renderer/build.dev.js:8415:27)
    at waitForServerPrefetch (/github/workspace/node_modules/vue-server-renderer/build.dev.js:8287:3)
    at renderComponentInner (/github/workspace/node_modules/vue-server-renderer/build.dev.js:8426:3)
error Command failed with exit code 1.
wait Rendering static HTML...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by scil** [comment]
I encounter the same error with another auto-sidebar plugin [vuepress-plugin-auto-sidebar](https://github.com/shanyuhai123/vuepress-plugin-auto-sidebar).

I found this issue stem from vuepress. 

Now I use vuepress v2 and yarn,  work well.
